myapp/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/products', 'ProductController')->except(['show']);
Route::resource('/orders', 'OrderController')->except(['show']);
Route::get('/', 'OrderController@create')->name('home');

myapp/app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Order extends Model
{
    const TABLE_NAME = 'orders';
    const ID = 'id';
    const CUSTOMER_NAME = 'customer_name';

    /**
     * @return BelongsToMany
     */
    public function products() : BelongsToMany
    {
        return $this->belongsToMany(Product::class)->withPivot(Product::PIVOT_COUNT);
    }

    /**
     * @param string $customerName
     * @return Order
     */
    public static function createFactory(string $customerName) : Order
    {
        $order = new self();
        $order->setCustomerName($customerName)->save();

        return $order;
    }

    /**
     * @param string $customerName
     * @return Order
     */
    public function updateFactory(string $customerName) : Order
    {
        $this->setCustomerName($customerName)->save();

        return $this;
    }

    /**
     * @param string $name
     * @return Order
     */
    public function setCustomerName(string $name) : Order
    {
        $this->{self::CUSTOMER_NAME} = strtolower($name);

        return $this;
    }

    /**
     * @return string|null
     */
    public function getCustomerName() : ?string
    {
        return $this->{self::CUSTOMER_NAME};
    }
}

myapp/app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\OrderRequest;
use App\Order;
use App\Product;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Session;
use Illuminate\View\View;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index() : View
    {
        return view('orders.index', ['orders' => Order::paginate(20)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create() : View
    {
        return view('orders.manage', ['method' => 'POST', 'route' => route('orders.store')]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param OrderRequest $request
     * @return RedirectResponse
     */
    public function store(OrderRequest $request) : RedirectResponse
    {
        $order = Order::createFactory($request->get(OrderRequest::CUSTOMER_NAME));
        $products = [];
        foreach ($request->get('products') as $product) {
            $count = $request->has('count' . $product) ?
                $request->get('count' . $product) :
                1;
            $order->products()->attach((int)$product, [Product::PIVOT_COUNT => $count]);
            $products[] = [
                (int)$product => [

                ]
            ];
        }
        Session::flash('message', 'Order has been saved.');
        Session::flash('alert-class', 'alert-success');

        return redirect('/orders');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Order $order
     * @return View
     */
    public function edit(Order $order) : View
    {
        return view(
            'orders.manage',
            ['order' => $order, 'method' => 'PUT', 'route' => route('orders.update', $order)]
        );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param OrderRequest $request
     * @param Order $order
     * @return RedirectResponse
     */
    public function update(OrderRequest $request, Order $order) : RedirectResponse
    {
        $order->updateFactory($request->get(OrderRequest::CUSTOMER_NAME));
        $products = [];
        foreach ($request->{OrderRequest::PRODUCTS} as $product) {
            $products[(int)$product] = [
                Product::PIVOT_COUNT => $request->has('count' . $product) ?
                    $request->get('count' . $product) :
                    1
            ];
        }
        $order->products()->sync($products);
        Session::flash('message', 'Order has been updated.');
        Session::flash('alert-class', 'alert-success');

        return redirect('/orders');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Order $order
     * @return RedirectResponse
     */
    public function destroy(Order $order) : RedirectResponse
    {
        try {
            $order->delete();
            Session::flash('message', 'Order has been deleted.');
            Session::flash('alert-class', 'alert-success');
        } catch (\Exception $exception) {
            Session::flash('message', 'Can not delete order!');
            Session::flash('alert-class', 'alert-danger');
        }

        return redirect('/orders');
    }
}

myapp/resources/views/orders/index.blade.php
@extends('master')
@section('content')
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                    لیست سفارشات

                </header>
                <table class="table table-striped table-advance table-hover">
                    <thead>
                    <tr>
                        <th><i class="icon-bullhorn"></i>نام مشتری</th>
                        <th class="hidden-phone"><i class="icon-question-sign"></i>تاریخ سفارش</th>
                        <th><i class="icon-bookmark"></i>قیمت کل</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($orders as $order)
                        <tr>
                            <td>{!! $order->getCustomerName() !!}</td>
                            <td class="hidden-phone">{!! $order->{\App\Order::CREATED_AT} !!}</td>
                            <?php
                            $sum= 0;
                            foreach ($order->products as $product) {
                                $sum += $product->getCost() * $product->pivot->count;
                            }
                            ?>
                            <td>{!! $sum !!}</td>
                            <td>
                                <a type="button" class="btn btn-primary btn-xs"
                                   href="{!! route('orders.edit', $order) !!}">
                                    <i class="icon-pencil"></i>
                                </a>
                                <form method="post" class="inline-block"
                                      action="{!! route('orders.destroy', $order) !!}">
                                    @csrf
                                    @method('delete')
                                    <button type="submit" class="btn btn-danger btn-xs">
                                        <i class="icon-trash "></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </section>
        </div>
    </div>
@endsection

myapp/resources/views/orders/manage.blade.php
@extends('master')
@section('content')
    <section class="panel">
        <header class="panel-heading">
            ثبت سفارش
        </header>
        <div class="panel-body">
            <form class="form-horizontal tasi-form" method="post" action="{!! $route !!}">
                @csrf
                @method($method)
                <div class="form-group">
                    <label class="col-sm-2 control-label">نام مشتری</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="customer_name"
                        @if(isset($order))
                            value="{!! $order->getCustomerName() !!}"
                            @endif>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">محصولات اصلی</label>
                    <div class="col-sm-10">
                    @foreach(\App\Product::whereTypeIs(\App\Product::TYPE_MAIN)->get() as $main)
                            <div class="row">
                                <div class="checkbox col-sm-6">
                                    <label>
                                        <input class="main" type="checkbox" name="products[]" value="{!! $main->getId() !!}"
                                              onclick="checkFunction()"
                                        @if(isset($order) && $order->products()->whereIdIs($main->getId())->first())
                                            checked="checked"
                                            @endif
                                        >
                                        {!! $main->getTitle() !!}
                                    </label>
                                </div>
                                <div class="col-sm-2">
                                    تعداد
                                    <input type="text" class="form-control" name="count{!! $main->getId() !!}"
                                           @if(isset($order) && $order->products()->whereIdIs($main->getId())->first())
                                           value="{!! $order->products()->whereIdIs($main->getId())->first()->pivot->count !!}"
                                           @else
                                           value="1"
                                           @endif
                                    >
                                </div>
                                <div class="col-sm-4"> قیمت {!! $main->getCost() !!}</div>
                            </div>
                    @endforeach
                    </div>
                </div>
                <div class="form-group" id="additionals"
                     @if(!isset($order))
                     style="display: none"
                     @endif
                >
                    <label class="col-sm-2 control-label">محصولات جانبی</label>
                    @foreach(\App\Product::whereTypeIs(\App\Product::TYPE_ADDITIONAL)->get() as $additional)
                        <div class="col-sm-10">
                            <div class="row">
                                <div class="checkbox col-sm-6">
                                    <label>
                                        <input type="checkbox" name="products[]" value="{!! $additional->getId() !!}"
                                               @if(isset($order) && $order->products()->whereIdIs($additional->getId())->first())
                                               checked="checked"
                                            @endif
                                        >
                                        {!! $additional->getTitle() !!}
                                    </label>
                                </div>
                                <div class="col-sm-2">
                                    <input type="text" class="form-control" name="count{!! $additional->getId() !!}"
                                           @if(isset($order) && $check = $order->products()->whereIdIs($additional->getId())->first())
                                           value="{!! $check->pivot->count !!}"
                                           @else
                                           value="1"
                                        @endif
                                    >
                                </div>
                                <div class="col-sm-4"> قیمت {!! $additional->getCost() !!}</div>
                            </div>
                        </div>
                    @endforeach
                </div>
                <button type="submit" class="btn btn-info">ثبت</button>
            </form>
        </div>
    </section>
@endsection

@section('js')
    <script type="application/javascript">
        function checkFunction() {
            if ($('.main:checked').length > 0) {
                document.getElementById("additionals").style.display = "block";
            } else {
                document.getElementById("additionals").style.display = "none";
            }
        }
    </script>
@endsection