myapp/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/products', 'ProductController')->except(['show']);
Route::resource('/orders', 'OrderController')->except(['show']);
Route::get('/', 'OrderController@create')->name('home');

myapp/app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Product extends Model
{
    const TABLE_NAME = 'products';
    const ID = 'id';
    const TITLE = 'title';
    const PRODUCT_TYPE = 'product_type';
    const TYPE_MAIN = 'main';
    const TYPE_ADDITIONAL = 'additional';
    const COST = 'cost';
    const PIVOT_COUNT = 'count';

    public $timestamps = false;

    public static $types = [self::TYPE_MAIN, self::TYPE_ADDITIONAL];

    /**
     * @return BelongsToMany
     */
    public function orders() : BelongsToMany
    {
        return $this->belongsToMany(Order::class)->withPivot(self::PIVOT_COUNT);
    }

    /**
     * @param string $title
     * @param string $type
     * @param int|null $cost
     * @return Product
     * @throws \Exception
     */
    public static function createFactory(string $title, string $type, ?int $cost = 0) : Product
    {
        $product = new self();
        $product->setTitle($title)
            ->setProductType($type)
            ->setCost($cost)
            ->save();
        
        return $product;
    }

    /**
     * @param string $title
     * @param string $type
     * @param int|null $cost
     * @return Product
     * @throws \Exception
     */
    public function updateFactory(string $title, string $type, ?int $cost = 0) : Product
    {
        $this->setTitle($title)
            ->setProductType($type)
            ->setCost($cost)
            ->save();
        
        return $this;
    }

    /**
     * @param Builder $builder
     * @param string $type
     * @return Builder
     */
    public function scopeWhereTypeIs(Builder $builder, string $type) : Builder
    {
        return $builder->where(self::PRODUCT_TYPE, $type);
    }

    /**
     * @param Builder $builder
     * @param int $id
     * @return Builder
     */
    public function scopeWhereIdIs(Builder $builder, int $id) : Builder
    {
        return $builder->where(self::ID, $id);
    }

    /**
     * @return int|null
     */
    public function getId() : ?int
    {
        return $this->{self::ID};
    }

    /**
     * @param int $cost
     * @return Product
     */
    public function setCost(int $cost) : Product
    {
        $this->{self::COST} = $cost;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getCost() : ?int
    {
        return $this->{self::COST};
    }

    /**
     * @param string $type
     * @return Product
     * @throws \Exception
     */
    public function setProductType(string $type) : Product
    {
        if (!in_array($type, self::$types)) {
            throw new \Exception('PRODUCT_TYPE is not valid!');
        }

        $this->{self::PRODUCT_TYPE} = $type;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getProductType() : ?string
    {
        return $this->{self::PRODUCT_TYPE};
    }

    /**
     * @param string $title
     * @return Product
     */
    public function setTitle(string $title) : Product
    {
        $this->{self::TITLE} = strtolower($title);

        return $this;
    }

    /**
     * @return string|null
     */
    public function getTitle() : ?string
    {
        return $this->{self::TITLE};
    }
}

myapp/app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductRequest;
use App\Product;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Session;
use Illuminate\View\View;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index() : View
    {
        return view('products.index', ['products' => Product::paginate(20)]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create() : View
    {
        return view('products.manage', ['method' => 'POST', 'route' => route('products.store')]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ProductRequest $request
     * @return RedirectResponse
     * @throws \Exception
     */
    public function store(ProductRequest $request) : RedirectResponse
    {
        Product::createFactory($request->get('title'), $request->get('product_type'), $request->get('cost'));
        Session::flash('message', 'Product has been saved.');
        Session::flash('alert-class', 'alert-success');

        return redirect('/products');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Product $product
     * @return View
     */
    public function edit(Product $product) : View
    {
        return view(
            'products.manage',
            ['product' => $product, 'method' => 'PUT', 'route' => route('products.update', $product)]
        );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ProductRequest $request
     * @param Product $product
     * @return RedirectResponse
     * @throws \Exception
     */
    public function update(ProductRequest $request, Product $product) : RedirectResponse
    {
        $product->updateFactory(
            $request->get('title'),
            $request->get('product_type'),
            $request->get('cost')
        );
        Session::flash('message', 'Product has been updated.');
        Session::flash('alert-class', 'alert-success');

        return redirect('/products');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Product $product
     * @return RedirectResponse
     */
    public function destroy(Product $product) : RedirectResponse
    {
        try {
            $product->delete();
            Session::flash('message', 'Product has been deleted.');
            Session::flash('alert-class', 'alert-success');
        } catch (\Exception $exception) {
            Session::flash('message', 'Can not delete product!');
            Session::flash('alert-class', 'alert-danger');
        }

        return redirect('/products');
    }
}

myapp/resources/views/products/index.blade.php
@extends('master')
@section('content')
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                    لیست محصولات

                </header>
                <table class="table table-striped table-advance table-hover">
                    <thead>
                    <tr>
                        <th><i class="icon-bullhorn"></i>عنوان</th>
                        <th class="hidden-phone"><i class="icon-question-sign"></i>نوع محصول</th>
                        <th><i class="icon-bookmark"></i>قیمت</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach($products as $product)
                            <tr>
                                <td>{!! $product->getTitle() !!}</td>
                                <td class="hidden-phone">{!! $product->getProductType() !!}</td>
                                <td>{!! $product->getCost() !!}</td>
                                <td>
                                    <a type="button" class="btn btn-primary btn-xs"
                                       href="{!! route('products.edit', $product->getId()) !!}">
                                        <i class="icon-pencil"></i>
                                    </a>
                                    <form method="post" class="inline-block"
                                          action="{!! route('products.destroy', $product) !!}">
                                        @csrf
                                        @method('delete')
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <i class="icon-trash "></i>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </section>
        </div>
    </div>
@endsection

myapp/resources/views/products/manage.blade.php
@extends('master')
@section('content')
    <section class="panel">
        <header class="panel-heading">
            ثبت محصول
        </header>
        <div class="panel-body">
            <form class="form-horizontal tasi-form" method="post" action="{!! $route !!}">
                @csrf
                @method($method)
                <div class="form-group">
                    <label class="col-sm-2 control-label">عنوان</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="title"
                        @if(isset($product))
                            value="{!! $product->getTitle() !!}"
                        @else
                            value=""
                        @endif
                        >
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">قیمت</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="cost"
                        @if(isset($product))
                            value="{!! $product->getCost() !!}"
                        @else
                            value=""
                        @endif
                        >
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">نوع محصول</label>
                    <div class="col-sm-10">
                        <select class="form-control m-bot15" name="product_type">
                            @foreach(\App\Product::$types as $type)
                                <option value="{!! $type !!}"
                                @if(isset($product) && $product->getProductType() == $type)
                                    selected="selected"
                                @endif
                                >{!! ucwords($type) !!}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <button type="submit" class="btn btn-info">ثبت</button>
            </form>
        </div>
    </section>
@endsection